### ISSUE TITLE
epic(ui): redesign

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.docs#183]
This epic will contain issues for refreshing the look and fill with the CodeX Docs

## Main
- [x] https://github.com/codex-team/codex.docs/issues/172
- [x] https://github.com/codex-team/codex.docs/issues/179
- [x] https://github.com/codex-team/codex.docs/issues/173
- [x] https://github.com/codex-team/codex.docs/issues/174
- [x] https://github.com/codex-team/codex.docs/issues/176
- [x] https://github.com/codex-team/codex.docs/issues/178
- [x] https://github.com/codex-team/codex.docs/issues/180
- [x] https://github.com/codex-team/codex.docs/issues/181

## Additional 
- [x] https://github.com/codex-team/codex.docs/issues/171
- [x] https://github.com/codex-team/codex.docs/issues/175
- [x] https://github.com/codex-team/codex.docs/issues/177
- [x] https://github.com/codex-team/codex.docs/issues/182
- [x] https://github.com/codex-team/codex.docs/issues/196

## Things left (design required)

- [ ] Mobile version updates
- [ ] Select dropdown design
- [x] Table of Contents nesting

![Document Overview](https://user-images.githubusercontent.com/3684889/164715528-2487ac5e-c42f-40f0-a796-8491fd87fada.png)

**Comment by nikmel2803** [comment]
done
